# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27d7e9e5f73d6063be1941b88747ffcb4391da547ec18d85caab8f4bcc8c60b41d92e23fb2463a8a67536423297e977f292a62ccd5912d855fb8b0baa15b6864

test:
  secret_key_base: d7a69d372cd43a22a6dd7ca61c976419fd2cf6dc4ab86c2305e25dc2a0db50f62b87ea69afd842e19f6157c0ca07323a9784988c9390a9b6fbde88966b3f6386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
